chord_dictionary = {
    "aug": ("img/chords/aug/1.png", "img/chords/aug/2.png", "img/chords/aug/3.png", "img/chords/aug/4.png",
            "img/chords/aug/5.png", "img/chords/aug/6.png"),
    "aug7": ("img/chords/aug7/1.png", "img/chords/aug7/2.png", "img/chords/aug7/3.png", "img/chords/aug7/4.png",
             "img/chords/aug7/5.png", "img/chords/aug7/6.png"),
    "augmajor7": ("img/chords/augmajor7/1.png", "img/chords/augmajor7/2.png", "img/chords/augmajor7/3.png",
                  "img/chords/augmajor7/4.png",
                  "img/chords/augmajor7/5.png", "img/chords/augmajor7/6.png"),
    "dim": ("img/chords/dim/1.png", "img/chords/dim/2.png", "img/chords/dim/3.png", "img/chords/dim/4.png",
            "img/chords/dim/5.png", "img/chords/dim/6.png"),
    "dim7": ("img/chords/dim7/1.png", "img/chords/dim7/2.png", "img/chords/dim7/3.png", "img/chords/dim7/4.png",
             "img/chords/dim7/5.png", "img/chords/dim7/6.png"),
    "dom7": ("img/chords/dom7/1.png", "img/chords/dom7/2.png", "img/chords/dom7/3.png", "img/chords/dom7/4.png",
             "img/chords/dom7/5.png", "img/chords/dom7/6.png"),
    "dom7sus4": (
        "img/chords/dom7sus4/1.png", "img/chords/dom7sus4/2.png", "img/chords/dom7sus4/3.png",
        "img/chords/dom7sus4/4.png",
        "img/chords/dom7sus4/5.png", "img/chords/dom7sus4/6.png"),
    "halfdim7": (
        "img/chords/halfdim7/1.png", "img/chords/halfdim7/2.png", "img/chords/halfdim7/3.png",
        "img/chords/halfdim7/4.png",
        "img/chords/halfdim7/5.png", "img/chords/halfdim7/6.png"),
    "major7": (
        "img/chords/major7/1.png", "img/chords/major7/2.png", "img/chords/major7/3.png", "img/chords/major7/4.png",
        "img/chords/major7/5.png", "img/chords/major7/6.png"),
    "major_triad": ("img/chords/major_triad/1.png", "img/chords/major_triad/2.png", "img/chords/major_triad/3.png",
                    "img/chords/major_triad/4.png",
                    "img/chords/major_triad/5.png", "img/chords/major_triad/6.png"),
    "minor7": (
        "img/chords/minor7/1.png", "img/chords/minor7/2.png", "img/chords/minor7/3.png", "img/chords/minor7/4.png",
        "img/chords/minor7/5.png", "img/chords/minor7/6.png"),
    "minor_triad": ("img/chords/minor_triad/1.png", "img/chords/minor_triad/2.png", "img/chords/minor_triad/3.png",
                    "img/chords/minor_triad/4.png",
                    "img/chords/minor_triad/5.png", "img/chords/minor_triad/6.png"),
    "minormajor7": ("img/chords/minormajor7/1.png", "img/chords/minormajor7/2.png", "img/chords/minormajor7/3.png",
                    "img/chords/minormajor7/4.png",
                    "img/chords/minormajor7/5.png", "img/chords/minormajor7/6.png"),
    "sus2": ("img/chords/sus2/1.png", "img/chords/sus2/2.png", "img/chords/sus2/3.png", "img/chords/sus2/4.png",
             "img/chords/sus2/5.png", "img/chords/sus2/6.png"),
    "sus4": ("img/chords/sus4/1.png", "img/chords/sus4/2.png", "img/chords/sus4/3.png", "img/chords/sus4/4.png",
             "img/chords/sus4/5.png", "img/chords/sus4/6.png")
}
