ear_note_dictionary = {
    "A": ("sounds/notes/a-1.flac", "sounds/notes/a0.flac", "sounds/notes/a1.flac",
          "sounds/notes/a2.flac", "sounds/notes/a3.flac", "sounds/notes/a4.flac",
          "sounds/notes/a5.flac", "sounds/notes/a6.flac"),
    "Ais": ("sounds/notes/ais-1.flac", "sounds/notes/ais0.flac", "sounds/notes/ais1.flac",
            "sounds/notes/ais2.flac", "sounds/notes/a3.flac", "sounds/notes/ais4.flac",
            "sounds/notes/ais5.flac", "sounds/notes/ais6.flac"),
    "B": ("sounds/notes/b-1.flac", "sounds/notes/b0.flac", "sounds/notes/b1.flac",
          "sounds/notes/b2.flac", "sounds/notes/b3.flac", "sounds/notes/b4.flac",
          "sounds/notes/b5.flac", "sounds/notes/b6.flac"),
    "C": ("sounds/notes/c7.flac", "sounds/notes/c0.flac", "sounds/notes/c1.flac",
          "sounds/notes/c2.flac", "sounds/notes/c3.flac", "sounds/notes/c4.flac",
          "sounds/notes/c5.flac", "sounds/notes/c6.flac"),
    "Cis": ("sounds/notes/cis0.flac", "sounds/notes/cis1.flac", "sounds/notes/cis2.flac",
            "sounds/notes/cis3.flac", "sounds/notes/cis4.flac", "sounds/notes/cis5.flac",
            "sounds/notes/cis6.flac"),
    "D": ("sounds/notes/d0.flac", "sounds/notes/d1.flac", "sounds/notes/d2.flac",
          "sounds/notes/d3.flac", "sounds/notes/d4.flac", "sounds/notes/d5.flac",
          "sounds/notes/d6.flac"),
    "Dis": ("sounds/notes/dis0.flac", "sounds/notes/dis1.flac", "sounds/notes/dis2.flac",
            "sounds/notes/dis3.flac", "sounds/notes/dis4.flac", "sounds/notes/dis5.flac",
            "sounds/notes/dis6.flac"),
    "E": ("sounds/notes/e0.flac", "sounds/notes/e1.flac", "sounds/notes/e2.flac",
          "sounds/notes/e3.flac", "sounds/notes/e4.flac", "sounds/notes/e5.flac",
          "sounds/notes/e6.flac"),
    "F": ("sounds/notes/f0.flac", "sounds/notes/f1.flac", "sounds/notes/f2.flac",
          "sounds/notes/f3.flac", "sounds/notes/f4.flac", "sounds/notes/f5.flac",
          "sounds/notes/f6.flac"),
    "Fis": ("sounds/notes/fis0.flac", "sounds/notes/fis1.flac", "sounds/notes/fis2.flac",
            "sounds/notes/fis3.flac", "sounds/notes/fis4.flac", "sounds/notes/fis5.flac",
            "sounds/notes/fis6.flac"),
    "G": ("sounds/notes/g0.flac", "sounds/notes/g1.flac", "sounds/notes/g2.flac",
          "sounds/notes/g3.flac", "sounds/notes/g4.flac", "sounds/notes/g5.flac",
          "sounds/notes/g6.flac"),
    "Gis": ("sounds/notes/gis0.flac", "sounds/notes/gis1.flac", "sounds/notes/gis2.flac",
            "sounds/notes/gis3.flac", "sounds/notes/gis4.flac", "sounds/notes/gis5.flac",
            "sounds/notes/gis6.flac"),
}
