ear_interval_dictionary = {
    "minor2": ('sounds/intervals/minor2/1.flac', 'sounds/intervals/minor2/2.flac', 'sounds/intervals/minor2/3.flac',
               'sounds/intervals/minor2/4.flac', 'sounds/intervals/minor2/5.flac', 'sounds/intervals/minor2/6.flac',
               'sounds/intervals/major2/7.flac'),
    "major2": ('sounds/intervals/major2/1.flac', 'sounds/intervals/major2/2.flac', 'sounds/intervals/major2/3.flac',
               'sounds/intervals/major2/4.flac', 'sounds/intervals/major2/5.flac', 'sounds/intervals/major2/6.flac',
               'sounds/intervals/major2/7.flac'),
    "minor3": ('sounds/intervals/minor3/1.flac', 'sounds/intervals/minor3/2.flac', 'sounds/intervals/minor3/3.flac',
               'sounds/intervals/minor3/4.flac', 'sounds/intervals/minor3/5.flac', 'sounds/intervals/minor3/6.flac',
               'sounds/intervals/minor3/7.flac'),
    "major3": ('sounds/intervals/major3/1.flac', 'sounds/intervals/major3/2.flac', 'sounds/intervals/major3/3.flac',
               'sounds/intervals/major3/4.flac', 'sounds/intervals/major3/5.flac', 'sounds/intervals/major3/6.flac',
               'sounds/intervals/major3/7.flac'),
    "4": ('sounds/intervals/4/1.flac', 'sounds/intervals/4/2.flac', 'sounds/intervals/4/3.flac',
          'sounds/intervals/4/4.flac', 'sounds/intervals/4/5.flac', 'sounds/intervals/4/6.flac',
          'sounds/intervals/4/7.flac'),
    "tritone": ('sounds/intervals/tritone/1.flac', 'sounds/intervals/tritone/2.flac', 'sounds/intervals/tritone/3.flac',
                'sounds/intervals/tritone/4.flac', 'sounds/intervals/tritone/5.flac', 'sounds/intervals/tritone/6.flac',
                'sounds/intervals/tritone/7.flac'),
    "5": ('sounds/intervals/5/1.flac', 'sounds/intervals/5/2.flac', 'sounds/intervals/5/3.flac',
          'sounds/intervals/5/4.flac', 'sounds/intervals/5/5.flac', 'sounds/intervals/5/6.flac',
          'sounds/intervals/5/7.flac'),
    "minor6": ('sounds/intervals/minor6/1.flac', 'sounds/intervals/minor6/2.flac', 'sounds/intervals/minor6/3.flac',
               'sounds/intervals/minor6/4.flac', 'sounds/intervals/minor6/5.flac', 'sounds/intervals/minor6/6.flac',
               'sounds/intervals/minor6/7.flac'),
    "major6": ('sounds/intervals/major6/1.flac', 'sounds/intervals/major6/2.flac', 'sounds/intervals/major6/3.flac',
               'sounds/intervals/major6/4.flac', 'sounds/intervals/major6/5.flac', 'sounds/intervals/major6/6.flac',
               'sounds/intervals/major6/7.flac'),
    "minor7": ('sounds/intervals/minor7/1.flac', 'sounds/interval/minor7/2.flac', 'sounds/interval/minor7/3.flac',
               'sounds/intervals/minor7/4.flac', 'sounds/interval/minor7/5.flac', 'sounds/interval/minor7/6.flac',
               'sounds/intervals/minor7/7.flac'),
    "major7": ('sounds/intervals/major7/1.flac', 'sounds/intervals/major7/2.flac', 'sounds/intervals/major7/3.flac',
               'sounds/intervals/major7/4.flac', 'sounds/intervals/major7/5.flac', 'sounds/intervals/major7/6.flac',
               'sounds/intervals/major7/7.flac'),
    "8": ('sounds/intervals/8/1.flac', 'sounds/intervals/8/2.flac', 'sounds/intervals/8/3.flac',
          'sounds/intervals/8/4.flac', 'sounds/intervals/8/5.flac', 'sounds/intervals/8/6.flac',
          'sounds/intervals/8/7.flac')
}
