interval_dictionary = {
    "aug2": ('img/intervals/aug2/1.png', 'img/intervals/aug2/2.png', 'img/intervals/aug2/3.png',
             'img/intervals/aug2/4.png', 'img/intervals/aug2/5.png'),
    "aug3": ('img/intervals/aug3/1.png', 'img/intervals/aug3/2.png', 'img/intervals/aug3/3.png',
             'img/intervals/aug3/4.png', 'img/intervals/aug3/5.png'),
    "aug4": ('img/intervals/aug4/1.png', 'img/intervals/aug4/2.png', 'img/intervals/aug4/3.png',
             'img/intervals/aug4/4.png', 'img/intervals/aug4/5.png'),
    "aug5": ('img/intervals/aug5/1.png', 'img/intervals/aug5/2.png', 'img/intervals/aug5/3.png',
             'img/intervals/aug5/4.png', 'img/intervals/aug5/5.png'),
    "aug6": ('img/intervals/aug6/1.png', 'img/intervals/aug6/2.png', 'img/intervals/aug6/3.png',
             'img/intervals/aug6/4.png', 'img/intervals/aug6/5.png'),
    "aug7": ('img/intervals/aug7/1.png', 'img/intervals/aug7/2.png', 'img/intervals/aug7/3.png',
             'img/intervals/aug7/4.png', 'img/intervals/aug7/5.png'),
    "aug8": ('img/intervals/aug8/1.png', 'img/intervals/aug8/2.png', 'img/intervals/aug8/3.png',
             'img/intervals/aug8/4.png', 'img/intervals/aug8/5.png'),
    "dim2": ('img/intervals/dim2/1.png', 'img/intervals/dim2/2.png', 'img/intervals/dim2/3.png',
             'img/intervals/dim2/4.png', 'img/intervals/dim2/5.png'),
    "dim3": ('img/intervals/dim3/1.png', 'img/intervals/dim3/2.png', 'img/intervals/dim3/3.png',
             'img/intervals/dim3/4.png', 'img/intervals/dim3/5.png'),
    "dim4": ('img/intervals/dim4/1.png', 'img/intervals/dim4/2.png', 'img/intervals/dim4/3.png',
             'img/intervals/dim4/4.png', 'img/intervals/dim4/5.png'),
    "dim5": ('img/intervals/dim5/1.png', 'img/intervals/dim5/2.png', 'img/intervals/dim5/3.png',
             'img/intervals/dim5/4.png', 'img/intervals/dim5/5.png'),
    "dim6": ('img/intervals/dim6/1.png', 'img/intervals/dim6/2.png', 'img/intervals/dim6/3.png',
             'img/intervals/dim6/4.png', 'img/intervals/dim6/5.png'),
    "dim7": ('img/intervals/dim7/1.png', 'img/intervals/dim7/2.png', 'img/intervals/dim7/3.png',
             'img/intervals/dim7/4.png', 'img/intervals/dim7/5.png'),
    "dim8": ('img/intervals/dim8/1.png', 'img/intervals/dim8/2.png', 'img/intervals/dim8/3.png',
             'img/intervals/dim8/4.png', 'img/intervals/dim8/5.png'),
    "min2": ('img/intervals/min2/1.png', 'img/intervals/min2/2.png', 'img/intervals/min2/3.png',
             'img/intervals/min2/4.png', 'img/intervals/min2/5.png'),
    "min3": ('img/intervals/min3/1.png', 'img/intervals/min3/2.png', 'img/intervals/min3/3.png',
             'img/intervals/min3/4.png', 'img/intervals/min3/5.png'),
    "min6": ('img/intervals/min6/1.png', 'img/intervals/min6/2.png', 'img/intervals/min6/3.png',
             'img/intervals/min6/4.png', 'img/intervals/min6/5.png'),
    "min7": ('img/intervals/min7/1.png', 'img/intervals/min7/2.png', 'img/intervals/min7/3.png',
             'img/intervals/min7/4.png', 'img/intervals/min7/5.png'),
    "maj2": ('img/intervals/maj2/1.png', 'img/intervals/maj2/2.png', 'img/intervals/maj2/3.png',
             'img/intervals/maj2/4.png', 'img/intervals/maj2/5.png'),
    "maj3": ('img/intervals/maj3/1.png', 'img/intervals/maj3/2.png', 'img/intervals/maj3/3.png',
             'img/intervals/maj3/4.png', 'img/intervals/maj3/5.png'),
    "maj6": ('img/intervals/maj6/1.png', 'img/intervals/maj6/2.png', 'img/intervals/maj6/3.png',
             'img/intervals/maj6/4.png', 'img/intervals/maj6/5.png'),
    "maj7": ('img/intervals/maj7/1.png', 'img/intervals/maj7/2.png', 'img/intervals/maj7/3.png',
             'img/intervals/maj7/4.png', 'img/intervals/maj7/5.png'),
    "p4": ('img/intervals/4/1.png', 'img/intervals/4/2.png', 'img/intervals/4/3.png',
           'img/intervals/4/4.png', 'img/intervals/4/5.png'),
    "p5": ('img/intervals/5/1.png', 'img/intervals/5/2.png', 'img/intervals/5/3.png',
           'img/intervals/5/4.png', 'img/intervals/5/5.png'),
    "p8": ('img/intervals/8/1.png', 'img/intervals/8/2.png', 'img/intervals/8/3.png',
           'img/intervals/8/4.png', 'img/intervals/8/5.png')
}
